### ISSUE TITLE
Is there more aggressive cache when you go back.

### ISSUE THREAD

**Issue by harish278** [box/viewer.js#159]
Hello,

We are using the non_svg: true option to generate the PNG and SVG assets for a large magazine ( https://www.dropbox.com/sh/9s1xvbsnukx6u70/AAC3lAt_9xkiTfcPkwGM8Jfba?dl=0 ) . When the Box Viewer starts, it loads a series of pages and assets proactively (13 or something). So that makes sure that the "next page" is loaded in the background. However, when you go back to the first page of the magazines, the viewer actually has to reload again the first few pages (which were loaded before). This causes some unexpected additional loading of the assets (when using PNG on low-end devices, it affects negatively the user experience).

Is there a way to achieve aggressive caching such that the assets wont load again and again once loaded already?

Thank in advance.

(cc @peetersn @jayant-simpragma)

**Comment by peetersn** [comment]
@lakenen Is there anything that we can do specifically to help you with reproduction of this issue?

**Comment by lakenen** [comment]
@harish278 @peetersn Sorry about the delay. I missed this issue somehow.

The viewer unloads pages pretty aggressively on mobile devices because there is typically not very much memory available, and using too much can cause the browser to crash. 

That said, it should not make additional network requests when the pages are reloaded. The page assets should be cached. The viewer just removes the img or svg elements from the DOM to free up memory.

Are you seeing additional network requests?

**Comment by harish278** [comment]
We don't see any additional network requests when we scroll back to pages that were loaded.

**Comment by lakenen** [comment]
@harish278 to be clear: is there any issue here?

**Comment by harish278** [comment]
Nope it's clear now. Thank you.
