### ISSUE TITLE
Tracking time users are spending on a document

### ISSUE THREAD

**Issue by brutman** [box/viewer.js#161]
Hi,

This is more of a question rather than an issue. Is there a way to track how long a user has spent on a document/ which pages did this user view? 

Thanks,

David.

**Comment by lakenen** [comment]
Hey David!

You could listen for `pagefocus` events (https://github.com/box/viewer.js#page-events) and use them to track how long the user has kept a specific page in focus. It's not necessary to use a plugin for this, but the docs contain an example plugin that implements page tracking (https://github.com/box/viewer.js#plugins).

As for how long they spent on the whole document, I think you'd have to track that within your app, because the viewer only knows about the one document it's currently showing. I'll close this issue, but please let me know if this doesn't answer your question.
