### ISSUE TITLE
Inconsistent zoom during layout update

### ISSUE THREAD

**Issue by zajca** [box/viewer.js#191]
Hi,
I want to implement doubletap zoom functionality. But I run to weird behavior during layout update.

I extend presentation layout with method setting zoom and scrolling based on tap position, but zoom and prevZoom values are changing during update.

Here is my plugin and layout:
https://gist.github.com/zajca/f10668cce4ebc5979dbb

This will happen:
- I get tap position and setZoom to 3 and pass position
- inside method: updateScrollPositionAfterClickZoom is prevZoom nad zoom right like this:
  prevZoom: 0.9110320284697508
  zoom: 3
- but in event zoom I get:
  prevZoom: 1.121953868019762
  zoom: 3.6945590263307007

so zoom value changed and view is not scrolled to place where was clicked.

Can I somehow avoid this and scroll to right place?

**Comment by lakenen** [comment]
I am not 100% on this, but I think the discrepancy between the zoom values in your method vs. the external event is caused by the adjustment to compensate for page scale (this is done automatically by the viewer so that the zoom values reported are accurate when the document has been artificially scaled up or down to fit properly). See https://github.com/box/viewer.js/blob/master/src/js/components/viewer-base.js#L240
